const dummyLaporan = [
  {
    id: 1,
    nama: "Siti Aminah",
    tanggal: "10 Januari 2024",
    provinsi: "Jawa Barat",
    kabupaten: "Bandung",
    lon: "5.31241234123",
    lat: "5.11213",
    kategori: "Sampah",
    deskripsi: "Tumpukan sampah di sungai Cikapundung menyebabkan bau tidak sedap dan mengganggu warga sekitar.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1300,
  },
  {
    id: 2,
    nama: "Budi Santoso",
    tanggal: "15 Februari 2024",
    provinsi: "Jawa Tengah",
    kabupaten: "Semarang",
    lon: "6.123456",
    lat: "7.654321",
    kategori: "Air",
    deskripsi: "Air bersih sulit didapat di daerah ini setelah kemarau panjang.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 980,
  },
  {
    id: 3,
    nama: "Rina Kartika",
    tanggal: "20 Maret 2024",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    lon: "6.20123",
    lat: "-106.84513",
    kategori: "Polusi",
    deskripsi: "Asap kendaraan menyebabkan sesak napas di kawasan Blok M.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1100,
  },
  {
    id: 4,
    nama: "Agus Wirawan",
    tanggal: "5 April 2024",
    provinsi: "Bali",
    kabupaten: "Denpasar",
    lon: "-8.65",
    lat: "115.21667",
    kategori: "Sampah",
    deskripsi: "Pantai penuh sampah plastik setelah musim liburan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 875,
  },
  {
    id: 5,
    nama: "Lina Marlina",
    tanggal: "12 Mei 2024",
    provinsi: "Sumatera Barat",
    kabupaten: "Padang",
    lon: "-0.95",
    lat: "100.35",
    kategori: "Limbah",
    deskripsi: "Limbah pabrik mencemari sungai Batang Arau.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 920,
  },
  {
    id: 6,
    nama: "Yusuf Hidayat",
    tanggal: "25 Mei 2024",
    provinsi: "Jawa Timur",
    kabupaten: "Surabaya",
    lon: "-7.250445",
    lat: "112.768845",
    kategori: "Polusi",
    deskripsi: "Udara di pusat kota terasa berat akibat kemacetan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1020,
  },
  {
    id: 7,
    nama: "Nani Rosdiana",
    tanggal: "1 Juni 2024",
    provinsi: "Kalimantan Timur",
    kabupaten: "Balikpapan",
    lon: "1.2675",
    lat: "116.8312",
    kategori: "Sampah",
    deskripsi: "TPS liar muncul di pinggir jalan utama.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 760,
  },
  {
    id: 8,
    nama: "Fajar Pratama",
    tanggal: "9 Juni 2024",
    provinsi: "Sulawesi Selatan",
    kabupaten: "Makassar",
    lon: "-5.147665",
    lat: "119.432732",
    kategori: "Limbah",
    deskripsi: "Limbah rumah tangga dibuang ke laut secara langsung.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 890,
  },
  {
    id: 9,
    nama: "Sari Lestari",
    tanggal: "18 Juni 2024",
    provinsi: "Riau",
    kabupaten: "Pekanbaru",
    lon: "0.5333",
    lat: "101.45",
    kategori: "Kebakaran Hutan",
    deskripsi: "Asap pekat menyelimuti kota akibat kebakaran lahan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1400,
  },
  {
    id: 10,
    nama: "Dian Ramadhan",
    tanggal: "22 Juni 2024",
    provinsi: "Aceh",
    kabupaten: "Banda Aceh",
    lon: "5.55",
    lat: "95.31667",
    kategori: "Sampah",
    deskripsi: "Sampah menumpuk di area pasar tradisional.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 610,
  },
  {
    id: 11,
    nama: "Ayu Wulandari",
    tanggal: "1 Juli 2024",
    provinsi: "NTB",
    kabupaten: "Mataram",
    lon: "-8.5833",
    lat: "116.1167",
    kategori: "Polusi",
    deskripsi: "Polusi suara dari industri mengganggu warga sekitar.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 720,
  },
  {
    id: 12,
    nama: "Rizky Maulana",
    tanggal: "4 Juli 2024",
    provinsi: "Papua",
    kabupaten: "Jayapura",
    lon: "-2.5337",
    lat: "140.7181",
    kategori: "Sampah",
    deskripsi: "Tidak tersedia tempat sampah umum di kompleks perumahan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 550,
  },
  {
    id: 13,
    nama: "Nadia Permata",
    tanggal: "10 Juli 2024",
    provinsi: "Banten",
    kabupaten: "Tangerang",
    lon: "-6.1783",
    lat: "106.63",
    kategori: "Limbah",
    deskripsi: "Cairan limbah industri meresap ke tanah warga.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 890,
  },
  {
    id: 14,
    nama: "Dede Sulaeman",
    tanggal: "14 Juli 2024",
    provinsi: "Jawa Barat",
    kabupaten: "Bekasi",
    lon: "-6.2349",
    lat: "106.9896",
    kategori: "Sampah",
    deskripsi: "Sungai Cikeas tercemar oleh sampah domestik.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1010,
  },
  {
    id: 15,
    nama: "Rosa Anggraini",
    tanggal: "20 Juli 2024",
    provinsi: "Kalimantan Barat",
    kabupaten: "Pontianak",
    lon: "0.02",
    lat: "109.33",
    kategori: "Polusi",
    deskripsi: "Debu batu bara dari pelabuhan mengganggu pernapasan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 800,
  },
  {
    id: 16,
    nama: "Darmawan Putra",
    tanggal: "1 Agustus 2024",
    provinsi: "Lampung",
    kabupaten: "Bandar Lampung",
    lon: "-5.45",
    lat: "105.2667",
    kategori: "Air",
    deskripsi: "Air keruh dan berbau di kran rumah warga.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 695,
  },
  {
    id: 17,
    nama: "Tiara Melati",
    tanggal: "9 Agustus 2024",
    provinsi: "Jambi",
    kabupaten: "Jambi",
    lon: "-1.6",
    lat: "103.6167",
    kategori: "Kebakaran Hutan",
    deskripsi: "Asap kebakaran hutan mengganggu aktivitas sekolah.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 1230,
  },
  {
    id: 18,
    nama: "Heri Gunawan",
    tanggal: "14 Agustus 2024",
    provinsi: "Maluku",
    kabupaten: "Ambon",
    lon: "-3.7",
    lat: "128.1667",
    kategori: "Sampah",
    deskripsi: "Pasar tradisional dipenuhi sampah sisa makanan.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 620,
  },
  {
    id: 19,
    nama: "Indah Puspita",
    tanggal: "22 Agustus 2024",
    provinsi: "Nusa Tenggara Timur",
    kabupaten: "Kupang",
    lon: "-10.1667",
    lat: "123.5833",
    kategori: "Limbah",
    deskripsi: "Limbah rumah tangga mengalir ke saluran irigasi sawah.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 760,
  },
  {
    id: 20,
    nama: "Andi Saputra",
    tanggal: "30 Agustus 2024",
    provinsi: "Bangka Belitung",
    kabupaten: "Pangkal Pinang",
    lon: "-2.13",
    lat: "106.12",
    kategori: "Air",
    deskripsi: "Sumur warga mengering dan tidak layak konsumsi.",
    foto: "../../assets/Laporan/contoh.png",
    upvote: 830,
  },
];

export default dummyLaporan;
